global:
  scrape_interval: 10s

rule_files:
  - "rules.yml"
alerting:
   alertmanagers:
      - static_configs:
        - targets:
           - "localhost:9093"  
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    scheme: https  
    tls_config:
      ca_file: ./node_exporter.crt
      insecure_skip_verify: true
    static_configs:
      - targets: ['localhost:9100']  
   
